### ISSUE TITLE
[PE-D][Tester E] Using "Persons" instead of "Contacts"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#158]
![image.png](https://raw.githubusercontent.com/yixiann/ped/main/files/bc5d40b9-f846-4e22-b4c1-1dde18444d2e.png)

![image.png](https://raw.githubusercontent.com/yixiann/ped/main/files/cbeeeb52-a1da-47a0-b91f-c0a641b68d42.png)

Proposed Fix:

Listed all contacts

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: yixiann/ped#2

**Comment by Eugene-Ong-W-X** [comment]
I will update the result display to show `Listed all contacts` instead
