### ISSUE TITLE
[PE-D][Tester B] Readibility of the Features section in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#159]
![image.png](https://raw.githubusercontent.com/PeiYee88/ped/main/files/03f8e2da-b31c-4bbb-a8c4-461b592ac594.png)

The list of features given seem too much for the reader at first sight. Perhaps you can group them into subsection such as general commands, commands for contacts, and commands for tags.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: PeiYee88/ped#1

**Comment by Eugene-Ong-W-X** [comment]
This might be feasible and/or helpful. I propose sectioning it into 

1. Contact Management Features
2. Tag Management Features
3. Customization Features
4. Todo Features
5. General Features (help, exit, saving data, editing data file)

What do the rest think?

**Comment by Ugholaf** [comment]
Yup I think we have to section it, but should the `Customization Features` be part of `Contact Management` since the customization is not to customise the whole app but only the fields in contact?

```
1 . Contact Management Features
    a. Contact Features
    b. Customization Features
2. Tag Management Features
3. Todo Management Features
4. General Features
```
Not sure if this is better.

**Comment by PangKuangWei** [comment]
> Yup I think we have to section it, but should the `Customization Features` be part of `Contact Management` since the customization is not to customise the whole app but only the fields in contact?
> 
> ```
> 1 . Contact Management Features
>     a. Contact Features
>     b. Customization Features
> 2. Tag Management Features
> 3. Todo Management Features
> 4. General Features
> ```
> 
> Not sure if this is better.

I agree but this might create issues such as confusing numbering of the bullet points as there's 1 more level of indentation.
