### ISSUE TITLE
[PE-D][Tester B] Consistency in the verb form used in the description of the feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#164]
![image.png](https://raw.githubusercontent.com/PeiYee88/ped/main/files/225d3319-8914-4ceb-ab27-396dde648acf.png)

`Sort contacts` can be changed to `sorting contacts` for consistency

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: PeiYee88/ped#3

**Comment by Eugene-Ong-W-X** [comment]
Will update sorting documentation to adhere to the verb format
