### ISSUE TITLE
[PE-D][Tester E] Table of contents do not have consistent description of commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-1/tp#166]
![image.png](https://raw.githubusercontent.com/yixiann/ped/main/files/12ec8b76-a1cf-4e91-83b7-55edaa5e5554.png)

viewing, editing, listing, adding 

v.s

sort 

Proposed fix:

Sorting all contacts

This is nearly a personal suggestion and not a bug

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yixiann/ped#5

**Comment by Eugene-Ong-W-X** [comment]
Will fix. Duplicate bug report. See #164
