### ISSUE TITLE
[PE-D][Tester E] What if individuals have the same name? Does this mean we cannot add them both into SoConnect?

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-1/tp#175]
No details provided by bug reporter.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: yixiann/ped#8

**Comment by Ugholaf** [comment]
Same issue: https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/210
