### ISSUE TITLE
[PE-D][Tester E] Sorting by name may be incorrect

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#183]
![image.png](https://raw.githubusercontent.com/yixiann/ped/main/files/56529169-0f12-4f88-bf8a-4063f1be8d67.png)

I feel A and AA should be together. Not sure why 'a' is between them.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yixiann/ped#10

**Comment by Eugene-Ong-W-X** [comment]
Documentation bug. Failed to mention that sorting in alphabetical order ignores case difference. Will fix.
