### ISSUE TITLE
[PE-D][Tester A] Searching bug #3

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#184]
Related to #1.

For some reason searching "search t/fr" gives result even if it is invalid tag. Maybe it is suppose to be able to find all tag that contains the word "fr" but it is not written in UG. But even if that is true, I'm not sure why "family" tag is inside.

<i><video controls><source src="https://raw.githubusercontent.com/LolfoollorS/ped/main/files/50d00bc9-68cf-4ed4-aef8-961114337cc3.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/LolfoollorS/ped/main/files/50d00bc9-68cf-4ed4-aef8-961114337cc3.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LolfoollorS/ped#5

**Comment by florentianayuwono** [comment]
Bug source identified: same as the previous thread of the reduction that happens in `containsSomeKeywordsIgnoreCase` before making sure that NONE of the contacts contain that.
