### ISSUE TITLE
[PE-D][Tester C] Overzealous error catching

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#191]
![image.png](https://raw.githubusercontent.com/cadencjk/ped/main/files/02372b1e-30e3-4ad2-b8b8-dfcbe33dbddd.png)

Typing Medium instead of medium throw me an error. Users may be accustomed to typing in Caps and will get frustrated over this. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cadencjk/ped#6

**Comment by Eugene-Ong-W-X** [comment]
Accepting other variations of `low`, `medium`, `high` is a more optimal design for priority which we did not have time to implement for v1.4.
I will add a mention of this in a suitable place in the UG as `Coming Soon` so that we can argue for `NotInScope`
