### ISSUE TITLE
[PE-D][Tester E] Improper handling of date that does not exist

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#193]
<i><video controls><source src="https://raw.githubusercontent.com/yixiann/ped/main/files/d8190211-b49e-4b07-85fb-2f8bcd8f0899.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/yixiann/ped/main/files/d8190211-b49e-4b07-85fb-2f8bcd8f0899.mov</i>

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yixiann/ped#12

**Comment by Ugholaf** [comment]
Same issue: https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/214
