### ISSUE TITLE
[PE-D][Tester A] Search bug #5

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#196]
Related to #1

Search 'and' ->  searches for contacts that match all the given information.

input: search t/colleagues and t/friends 

expected: Bernice Yu only 

actual: 
![image.png](https://raw.githubusercontent.com/LolfoollorS/ped/main/files/81279714-cf72-44fa-821a-495f5d3bc643.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LolfoollorS/ped#7

**Comment by florentianayuwono** [comment]
Seems like the tester misread the User Guide and provides input `search t/colleagues and t/friends` instead of `search and t/colleagues t/friends`. This of course put the search category into relevant search result. Will let the tester know.
