### ISSUE TITLE
[PE-D][Tester B] Usage on tag creation

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-1/tp#203]
Would be good to have a command so that I can view all the tags I have created.

This is because if I need to add a tag to a contact, I need to create a new tag if the tag does not exist. If it exists I can simply do add tag. But how will I know whether the tag has been created or not?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: PeiYee88/ped#12

**Comment by Ugholaf** [comment]
Feature flaw which we can't fix in v1.4.

**Comment by Eugene-Ong-W-X** [comment]
@ChongCheeKaiClarence can consider labeling this feature as coming soon `View all tags`

**Comment by ChongCheeKaiClarence** [comment]
Alright, then I'll update the ug accordingly.
