### ISSUE TITLE
[PE-D][Tester A] Customize show

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-1/tp#206]
Maybe it is better to have customize show all?

The reason being that it was quite annoying to keep typing out all four parameter to test out and I would assume that these "feature" might grow in the feature like instead of 4 maybe there might be 7-8. User might just want show all.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LolfoollorS/ped#9

**Comment by Ugholaf** [comment]
Hmmm I think it is too late to add this now since it is a feature flaw.

**Comment by Eugene-Ong-W-X** [comment]
Mhm, maybe @PangKuangWei can consider adding this enhancement as coming soon?
