### ISSUE TITLE
[PE-D][Tester B] Invalid command result for tag remove

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#209]
![image.png](https://raw.githubusercontent.com/PeiYee88/ped/main/files/0c1afba6-798e-4ebc-a412-ca4a2d44d063.png)

Tag `family` does exist in the contact book but command result shows up `this tag does not exist`

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: PeiYee88/ped#15

**Comment by ChongCheeKaiClarence** [comment]
Looks like i need to make it clearer.
