### ISSUE TITLE
[PE-D][Tester A] Cannot add a different person with same name 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#210]
If there is two person with same name but have different phone, address and email, this program will not accept it.

Reason being that there are alot of people in the world with the same name even in facebook and google has many people with the same name.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LolfoollorS/ped#10

**Comment by florentianayuwono** [comment]
I personally feel that this should be made a known limitation. If we allow for duplicate names, then there will be other people commenting that duplicate names are also bugs itself.

**Comment by ChongCheeKaiClarence** [comment]
Probably it can be clarified in the UG.
