### ISSUE TITLE
[PE-D][Tester A] Either incorrect error message was shown or for some reason the program think there is dupe task when it doesn't exist 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-1/tp#213]
<i><video controls><source src="https://raw.githubusercontent.com/LolfoollorS/ped/main/files/0d7f7400-6fd5-446f-b337-79d215d79d3f.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/LolfoollorS/ped/main/files/0d7f7400-6fd5-446f-b337-79d215d79d3f.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LolfoollorS/ped#13

**Comment by Ugholaf** [comment]
This should be caused by the date entered by the user auto changes to a valid date, e.g. `31-02-2022` is treated as `28-02-2022`.
